[deploy]
bucket = 'cfn-artifacts-0pagu5'
region = 'us-east-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'Benedicta-Onyekwere/aws-bootcamp-cruddur-2023'
ArtifactBucketName = "codepipeline-cruddur-artifacts-0pagu5"
BuildSpec = 'backend-flask/buildspec.yml'